### ISSUE TITLE
display all entries - hosty show command without parameters

### ISSUE THREAD

**Issue by c-nv-s** [areYouLazy/hosty#4]
**Is your feature request related to a problem? Please describe.**

it would be nice to be able to just type "hosty show" (without parameters) and receive all the current host file entries
or type "hosty show --json" and receive all the current entries in json format

**Comment by areYouLazy** [comment]
I'm working on it

**Comment by areYouLazy** [comment]
Implemented in [v1.1.0](https://github.com/areYouLazy/hosty/releases/tag/v1.1.0)

**Comment by c-nv-s** [comment]
not sure if you built the latest release on a new operating system but you seem to have introduced a dependency:
```
hosty: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by hosty)
```
which I don't think is installed by default on ubuntu <= groovy or debian <= 11

**Comment by areYouLazy** [comment]
lol! if I wanted to do it on purpose I wouldn't know how!
I'm going to take my other laptop to rebuild the packages

**Comment by areYouLazy** [comment]
Ok should be fixed [here](https://github.com/areYouLazy/hosty/releases/tag/v1.1.1)
@c-nv-s Can you confirm the unwanted dep is gone?

**Comment by c-nv-s** [comment]
@areYouLazy can confirm fixed.
could you please advise what the issue was because I have seen this in another project too.
perhaps I can pass on the knowledge in future

**Comment by areYouLazy** [comment]
I really don't know, all I can tell you is the "bad" package as been built on a fresh Ubuntu 21.04 installation with golang from ppa, while the "working" one has been built on a macOS 11.3.1 with golang from brew

**Comment by c-nv-s** [comment]
ok thanks, 
it would be interesting to see the difference if you installed golang on the 21.04 machine by downloading it directly from golang.org/dl and extracting it, then build a release and see if that glibc issue still exists when running the binary on older operating systems.

by the way, feel free to close this issue

**Comment by areYouLazy** [comment]
I downloaded golang from the website and compile hosty with it but the link to libc.so.6 seems to be there..
```bash
root@testmachine:~/go/src/github.com/areYouLazy/hosty|master ⇒ ldd hosty-test 
	linux-vdso.so.1 (0x00007fff84915000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f50ac241000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f50ac055000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f50ac278000)
```

**Comment by areYouLazy** [comment]
Going further, I think it's a static/dynamic compilation problem. While compiling directly to ubuntu (with go build) generates a dynamic linked executable, the one ported from the macOS (also done with go build) is not a dynamic executable:
```bash
root@testmachine:~/Downloads|⇒  ldd /usr/sbin/hosty 
	not a dynamic executable
```
So I think the cross-compilation from macOS generates a static binary, while the native compilation on Ubuntu generates a dynamic-linked binary. And NOW I can close the issue!

Thanks for your help!
